"""
check_earnings_calendar.py

作用：
1. 读取 data/company_master.csv
2. 使用 yfinance 查询每只股票的下一次 earnings date
3. 如果某家公司明天发布财报，发送邮件提醒
4. 记录已提醒事项，避免重复发送
"""

from datetime import date, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

import pandas as pd
import yfinance as yf

from send_email import send_email


BASE_DIR = Path(__file__).resolve().parents[1]

INPUT_FILE = BASE_DIR / "data" / "company_master.csv"
HISTORY_FILE = BASE_DIR / "data" / "earnings_alert_history.csv"

MARKET_TIMEZONE = ZoneInfo("America/New_York")


def today_et() -> date:
    """
    返回美东日期。

    GitHub Actions 用 UTC 运行，但财报提醒应该按美东交易日理解。
    """

    return datetime.now(MARKET_TIMEZONE).date()


def normalize_date(value) -> date | None:
    """
    把 yfinance 可能返回的日期类型统一成 date。
    """

    if value is None or pd.isna(value):
        return None

    if isinstance(value, pd.Timestamp):
        return value.date()

    if isinstance(value, datetime):
        return value.date()

    if isinstance(value, date):
        return value

    try:
        return pd.to_datetime(value).date()
    except Exception:
        return None


def get_earnings_dates(ticker: str) -> list[date]:
    """
    从 yfinance 获取一只股票的 earnings date。

    优先使用 calendar，因为它直接给未来财报日期；如果 calendar 没有数据，
    再 fallback 到 get_earnings_dates。
    """

    stock = yf.Ticker(ticker)
    dates: list[date] = []

    try:
        calendar = stock.get_calendar()
        earnings_dates = calendar.get("Earnings Date", [])

        if not isinstance(earnings_dates, list):
            earnings_dates = [earnings_dates]

        for earnings_date in earnings_dates:
            normalized = normalize_date(earnings_date)
            if normalized is not None:
                dates.append(normalized)

    except Exception as error:
        print(f"Warning: calendar lookup failed for {ticker}: {error}")

    if dates:
        return sorted(set(dates))

    try:
        earnings_df = stock.get_earnings_dates(limit=12)

        if earnings_df is None or earnings_df.empty:
            return []

        candidate_values = list(earnings_df.index)

        if "Earnings Date" in earnings_df.columns:
            candidate_values.extend(earnings_df["Earnings Date"].tolist())

        for earnings_date in candidate_values:
            normalized = normalize_date(earnings_date)
            if normalized is not None:
                dates.append(normalized)

    except Exception as error:
        print(f"Warning: earnings dates lookup failed for {ticker}: {error}")

    return sorted(set(dates))


def load_alert_history() -> pd.DataFrame:
    """
    读取已发送提醒记录。
    """

    columns = [
        "alert_date",
        "ticker",
        "company",
        "earnings_date",
        "sent_at",
    ]

    if not HISTORY_FILE.exists():
        return pd.DataFrame(columns=columns)

    return pd.read_csv(HISTORY_FILE)


def already_alerted(
    history: pd.DataFrame,
    ticker: str,
    earnings_date: date,
) -> bool:
    """
    判断同一 ticker、同一 earnings date 是否已经提醒过。
    """

    if history.empty:
        return False

    return (
        (history["ticker"] == ticker)
        & (history["earnings_date"] == earnings_date.isoformat())
    ).any()


def build_email_body(alerts: list[dict]) -> str:
    """
    生成邮件正文。
    """

    lines = [
        "以下公司明天有 earnings：",
        "",
    ]

    for alert in alerts:
        lines.append(
            f"- {alert['ticker']} ({alert['company']}): "
            f"earnings date = {alert['earnings_date']}"
        )

    lines.extend(
        [
            "",
            "This alert was generated by Investment OS.",
        ]
    )

    return "\n".join(lines)


def append_alert_history(alerts: list[dict]) -> None:
    """
    保存本次已发送提醒。
    """

    if not alerts:
        return

    HISTORY_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    existing = load_alert_history()
    new_rows = pd.DataFrame(alerts)

    combined = pd.concat(
        [existing, new_rows],
        ignore_index=True,
    )

    combined = combined.drop_duplicates(
        subset=["ticker", "earnings_date"],
        keep="last",
    )

    combined.to_csv(
        HISTORY_FILE,
        index=False,
    )

    print(f"\nUpdated earnings alert history: {HISTORY_FILE}")


def find_tomorrow_earnings(
    companies: pd.DataFrame,
    target_date: date,
) -> list[dict]:
    """
    找出 target_date 发布财报、且还没有提醒过的公司。
    """

    history = load_alert_history()
    alerts: list[dict] = []

    for _, company_row in companies.iterrows():
        ticker = str(company_row["ticker"]).strip().upper()
        company = company_row.get("company", "")

        if not ticker:
            continue

        print(f"Checking earnings calendar for {ticker}...")

        earnings_dates = get_earnings_dates(ticker)

        if target_date not in earnings_dates:
            continue

        if already_alerted(
            history,
            ticker,
            target_date,
        ):
            print(f"Already alerted for {ticker} earnings on {target_date}.")
            continue

        alerts.append(
            {
                "alert_date": today_et().isoformat(),
                "ticker": ticker,
                "company": company,
                "earnings_date": target_date.isoformat(),
                "sent_at": datetime.now(MARKET_TIMEZONE).strftime(
                    "%Y-%m-%d %H:%M:%S %Z"
                ),
            }
        )

    return alerts


def main() -> None:
    """
    主程序入口。
    """

    if not INPUT_FILE.exists():
        raise FileNotFoundError(f"Cannot find input file: {INPUT_FILE}")

    companies = pd.read_csv(INPUT_FILE)

    if "ticker" not in companies.columns:
        raise ValueError("company_master.csv must contain a 'ticker' column")

    target_date = today_et() + timedelta(days=1)

    print(f"\nChecking earnings calendar for: {target_date}\n")

    alerts = find_tomorrow_earnings(
        companies,
        target_date,
    )

    if not alerts:
        print("No earnings alerts for tomorrow.")
        return

    subject = f"Investment OS Earnings Alert: {target_date}"
    body = build_email_body(alerts)

    send_email(
        subject=subject,
        body=body,
    )

    append_alert_history(alerts)

    print(f"Sent {len(alerts)} earnings alert(s).")


if __name__ == "__main__":
    main()
